services:
  ubuntu24:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-24
    volumes:
      - .:/octopass
    environment:
      DIST: noble
    command: make deb
      #ubuntu22:
      #  dockerfile: dockerfiles/Dockerfile.ubuntu-22
      #  build: .
      #  volumes:
      #    - .:/octopass
      #  environment:
      #    DIST: jammy
      #  command: make deb
      #
      #debian11:
      #  dockerfile: dockerfiles/Dockerfile.debian-11
      #  build: .
      #  volumes:
      #    - .:/octopass
      #  environment:
      #    DIST: bullseye
      #    DEB_BUILD_OPTIONS: noautodbgsym
      #  command: make deb
