name: Build

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt install build-essential libcurl4-openssl-dev libjansson-dev linux-libc-dev libtool autoconf git bzip2 clang-format-10
        sudo make
  centos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [centos7, centos8]
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo yum install -y gcc make libcurl-devel jansson-devel bzip2 unzip rpmdevtools epel-release selinux-policy-devel
        sudo make
