name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages and Set envfile
      env:
        OCTOPASS_ENDPOINT: https://api.github.com/
        OCTOPASS_ORGANIZATION: ${{secrets.OCTOPASS_ORGANIZATION}}
        OCTOPASS_TEAM: ${{secrets.OCTOPASS_TEAM}}
        OCTOPASS_TOKEN: ${{secrets.OCTOPASS_TOKEN}}
      run: |
        sudo apt install build-essential libcurl4-openssl-dev libjansson-dev linux-libc-dev libtool autoconf git bzip2 clang-format-10
        env > .env
    - name: Unit Test
      run: sudo make test
    - name: Lint
      run: sudo make format
    - name: Integration Test
      run: sudo make integration
