name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt install build-essential libcurl4-openssl-dev libjansson-dev linux-libc-dev libtool autoconf git bzip2 clang-format-10
    - name: Test
      env:
        OCTOPASS_ENDPOINT: https://api.github.com/
        OCTOPASS_ORGANIZATION: ${{secrets.OCTOPASS_ORGANIZATION}}
        OCTOPASS_TEAM: ${{secrets.OCTOPASS_TEAM}}
        OCTOPASS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        sudo make test LIBDIR=/usr/lib/x86_64-linux-gnu OCTOPASS_ENDPOINT=$OCTOPASS_ENDPOINT OCTOPASS_TOKEN=$OCTOPASS_TOKEN OCTOPASS_ORGANIZATION=$OCTOPASS_ORGANIZATION OCTOPASS_TEAM=$OCTOPASS_TEAM
        sudo make format LIBDIR=/usr/lib/x86_64-linux-gnu
        sudo make integration_test LIBDIR=/usr/lib/x86_64-linux-gnu OCTOPASS_ENDPOINT=$OCTOPASS_ENDPOINT OCTOPASS_TOKEN=$OCTOPASS_TOKEN

